# Generated by Django 4.1.3 on 2022-11-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='giftcard/'),
        ),
    ]
