# Generated by Django 4.1.3 on 2022-11-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_coinpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinpay',
            name='coint_type',
            field=models.CharField(default='Bitcoin', max_length=70),
        ),
    ]
