# Generated by Django 4.1.3 on 2022-11-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_coinpay_coint_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinpay',
            old_name='coint_type',
            new_name='coin_type',
        ),
        migrations.AddField(
            model_name='giftcard',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
